-- ══════════════════════════════════════════════════════════════════════
--  BaaS Monitor — Migration v2
--  Yeni imkanlar / New features:
--    1. Sənəd yükləmə üçün storage_path sütunu (partner_docs)
--    2. Komisyon & limit paketləri (fee_packages cədvəli)
--    3. Supabase Storage bucket təlimatları
--
--  SQL Editor-da icra edin / Run in Supabase SQL Editor
-- ══════════════════════════════════════════════════════════════════════

-- ── 1. partner_docs: storage_path sütunu əlavə et ────────────────────
ALTER TABLE partner_docs
  ADD COLUMN IF NOT EXISTS storage_path TEXT DEFAULT '';

-- ── 2. fee_packages cədvəli ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS fee_packages (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id     BIGINT NOT NULL REFERENCES partners(id) ON DELETE CASCADE,
  name           TEXT NOT NULL DEFAULT '',
  status         TEXT NOT NULL DEFAULT 'active',   -- active | inactive
  effective_from TEXT DEFAULT '',
  effective_to   TEXT DEFAULT '',
  tiers          JSONB NOT NULL DEFAULT '[]',
  -- tiers format: [{"from":0,"to":500000,"rate":0.5}, {"from":500001,"to":null,"rate":0.3}]
  -- to: null = limitsiz / unlimited
  created_at     TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3. RLS ────────────────────────────────────────────────────────────
ALTER TABLE fee_packages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow_all" ON fee_packages FOR ALL TO anon USING (true) WITH CHECK (true);

-- ── 4. Nümunə məlumatlar / Sample data ───────────────────────────────
INSERT INTO fee_packages (id, partner_id, name, status, effective_from, effective_to, tiers)
VALUES
  (1, 1, 'AzərTech — 2024-2025 Komisyon Paketi', 'active', '2024-01-01', '2025-12-31',
   '[{"from":0,"to":500000,"rate":0.5},{"from":500001,"to":1000000,"rate":0.35},{"from":1000001,"to":null,"rate":0.2}]'::jsonb),

  (2, 2, 'FinTex Standart Tarif 2024', 'active', '2024-06-01', '2025-05-31',
   '[{"from":0,"to":300000,"rate":0.6},{"from":300001,"to":700000,"rate":0.4},{"from":700001,"to":null,"rate":0.25}]'::jsonb),

  (3, 4, 'MarketYer Premium Tarif', 'active', '2024-09-01', '2025-08-31',
   '[{"from":0,"to":1000000,"rate":0.45},{"from":1000001,"to":null,"rate":0.28}]'::jsonb),

  (4, 6, 'RəqəmsalBank VIP Tarif 2025', 'active', '2025-01-01', '2025-12-31',
   '[{"from":0,"to":200000,"rate":0.55},{"from":200001,"to":500000,"rate":0.38},{"from":500001,"to":1000000,"rate":0.25},{"from":1000001,"to":null,"rate":0.15}]'::jsonb);

-- Sequence sıfırla
SELECT setval(pg_get_serial_sequence('fee_packages','id'), (SELECT MAX(id) FROM fee_packages));

-- ══════════════════════════════════════════════════════════════════════
--  Supabase STORAGE bucket yaratmaq üçün təlimat
--  (SQL ilə mümkün deyil — Dashboard-dan edin):
--
--  1. Supabase Dashboard → Storage → New bucket
--  2. Bucket name:  partner-docs
--  3. Public bucket: ✓ (açıq qeyd edin)
--  4. Save
--
--  Sonra Policies → New Policy → "Allow all operations for anon":
--    Operation: SELECT, INSERT, UPDATE, DELETE
--    Target roles: anon
--    Policy: true
-- ══════════════════════════════════════════════════════════════════════
