-- ══════════════════════════════════════════════════════════════════════
--  BaaS Monitor — Migration v3
--  Yeni imkanlar / New features:
--    1. sys_users cədvəlinə password sütunu (autentifikasiya üçün)
--    2. mcc_data cədvəli — MCC kateqoriyaları üzrə əməliyyat statistikası
--    3. country_data cədvəli — ölkə üzrə əməliyyat statistikası
--
--  SQL Editor-da icra edin / Run in Supabase SQL Editor
-- ══════════════════════════════════════════════════════════════════════

-- ── 1. sys_users: password sütunu ─────────────────────────────────────
ALTER TABLE sys_users
  ADD COLUMN IF NOT EXISTS password TEXT NOT NULL DEFAULT '';

-- Mövcud istifadəçilər üçün demo şifrələr / Demo passwords for existing users
UPDATE sys_users SET password = 'admin123'   WHERE login = 'admin';
UPDATE sys_users SET password = 'analyst123' WHERE login = 'analyst';
UPDATE sys_users SET password = 'manager123' WHERE login = 'manager';
UPDATE sys_users SET password = 'viewer123'  WHERE login = 'viewer1';
UPDATE sys_users SET password = 'manager123' WHERE login = 'manager2';

-- ── 2. mcc_data cədvəli ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS mcc_data (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mcc        TEXT NOT NULL,
  label      TEXT NOT NULL DEFAULT '',
  txn_count  INTEGER NOT NULL DEFAULT 0,
  txn_volume NUMERIC(18,2) NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE mcc_data ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow_all" ON mcc_data FOR ALL TO anon USING (true) WITH CHECK (true);

-- Seed: MCC məlumatları (Azərbaycan bazarına uyğun)
INSERT INTO mcc_data (mcc, label, txn_count, txn_volume) VALUES
  ('5411', 'Ərzaq mağazaları',             28451, 315000.00),
  ('5812', 'Restoranlar və kafelər',        21302, 148000.00),
  ('5732', 'Elektronika',                    8920, 221000.00),
  ('5541', 'Yanacaqdoldurma stansiyaları',  15673, 102000.00),
  ('4814', 'Telekommunikasiya',              9840,  58000.00),
  ('7011', 'Otellər və mehmanxanalar',       3210,  89000.00),
  ('5999', 'Digər pərakəndə satış',         12804,  76000.00),
  ('5912', 'Əczaxanalar',                    6540,  42000.00),
  ('5311', 'Universal mağazalar',            4820,  67000.00),
  ('4111', 'Nəqliyyat xidmətləri',           7230,  38000.00)
ON CONFLICT DO NOTHING;

-- ── 3. country_data cədvəli ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS country_data (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code       TEXT NOT NULL,
  name       TEXT NOT NULL DEFAULT '',
  flag       TEXT NOT NULL DEFAULT '',
  txn_count  INTEGER NOT NULL DEFAULT 0,
  txn_volume NUMERIC(18,2) NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE country_data ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow_all" ON country_data FOR ALL TO anon USING (true) WITH CHECK (true);

-- Seed: Ölkə məlumatları
INSERT INTO country_data (code, name, flag, txn_count, txn_volume) VALUES
  ('AZ', 'Azərbaycan', '🇦🇿', 68204, 784000.00),
  ('TR', 'Türkiyə',    '🇹🇷', 12340, 103000.00),
  ('GE', 'Gürcüstan',  '🇬🇪',  5820,  42000.00),
  ('RU', 'Rusiya',     '🇷🇺',  3410,  51000.00),
  ('AE', 'BƏƏ',        '🇦🇪',  2180,  48000.00),
  ('DE', 'Almaniya',   '🇩🇪',  1840,  35000.00),
  ('US', 'ABŞ',        '🇺🇸',  1202,  26000.00),
  ('GB', 'Böyük Britaniya','🇬🇧', 890, 22000.00),
  ('FR', 'Fransa',     '🇫🇷',   740,  18000.00),
  ('IT', 'İtaliya',    '🇮🇹',   610,  15000.00)
ON CONFLICT DO NOTHING;

-- ── 4. Sequence-ləri sıfırla / Reset sequences ───────────────────────
SELECT setval(pg_get_serial_sequence('mcc_data',     'id'), (SELECT MAX(id) FROM mcc_data));
SELECT setval(pg_get_serial_sequence('country_data', 'id'), (SELECT MAX(id) FROM country_data));

-- ── Yoxlama / Verify ─────────────────────────────────────────────────
-- SELECT login, name, role, password FROM sys_users;
-- SELECT * FROM mcc_data ORDER BY txn_volume DESC;
-- SELECT * FROM country_data ORDER BY txn_volume DESC;
